---
# {page} : Number of pages players see when using /oplist
# {maxPage} : Maximum arguments the user can enter in /oplist [Arguments]
# {totalOpsOnline} : The number of operators is online in the server
opListTag: "&6- List of operators &f[&b{page} &6of &b{maxPage}&f] &f[&9Onlines&f: &a{totalOpsOnline}&f] &6-"

# {numericalOrder} : The ordinal number of the operator
# {opName} : Operator name
# {onlineStatus} : Operator online status
opListFormat: "&e» &a{numericalOrder}. &9{opName} &f[{onlineStatus}&f]"

# {onlineStatus} : Online Tag
onlineStatusTag: "&aOnline"
# {onlineStatus} : Offline Tag
offlineStatusTag: "&cOffline"

# The message sent to the user when the argument they entered does not exist
pageNotFound: "&e» §cPage not found!"

# Messages sent to users when the server does not have an operator
noOperator: "§e» §cNo operator!"

# Number of operators in a page
perPage: 5
...
